fix when quarkus-oidc is missing. Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.damdamdeo.pulse.extension.publisher.runtime.debezium.DebeziumConfigurator             at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)             at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1169)             at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationSupport.ensureClassInitialized(ClassInitializationSupport.java:288)             ... 25 more     Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "main"]             at io.smallrye.faulttolerance.api.SpiAccess.get(SpiAccess.java:18)             at io.smallrye.faulttolerance.api.TypedGuard.create(TypedGuard.java:64)             at com.damdamdeo.pulse.extension.publisher.runtime.debezium.DebeziumConfigurator.<clinit>(DebeziumConfigurator.java:21)             at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)             at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1169)